import type { Metadata } from 'next';
import { inter, poppins } from '@/config/fonts';
import './globals.css';
import SWRProvider from '@/providers/swr-provider';
import { getMeServer } from '@/lib/server/get-me';
import { SWR_KEYS } from '@/lib/constants/swr-keys';

export const metadata: Metadata = {
  title: 'FloodWatch',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getMeServer();

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable} bg-[#EAEAEA] antialiased min-h-screen`}
      >
        <SWRProvider fallback={{ [SWR_KEYS.me]: user }}>{children}</SWRProvider>
      </body>
    </html>
  );
}
