import type { Metadata } from 'next';
import { inter } from '@/app/config/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'FloodWatch',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#EAEAEA] antialiased min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
